TRACE Testing Sub RemoveHTMLTags.;
TRACE ;
TRACE Valid Use case...;

LET vHTMLData = '<div style="" ><div><p>:Tom went to the store to buy apples.<br>There were only 2 apples remaining.<br>So he bought the last 2 apples.</p></div></div>';

Call RemoveHTMLTags('$(vHTMLData)','vCleanedHTML');

TRACE Result: vCleanedHTML = '$(vCleanedHTML)';

TRACE Invalid Use cases...;
SET ErrorMode=0;

	TRACE Calling with no arguments...;
	Call RemoveHTMLTags;

	TRACE Calling with one text argument...;
	Call RemoveHTMLTags('$(vHTMLData)');

	TRACE Calling with one numeric argument...;
	Call RemoveHTMLTags(5);

	TRACE Calling with one text and one numeric value for UpdateVariable;
	Call RemoveHTMLTags('$(vHTMLData)',5);
    TRACE Result: 5 = '$(5)';

	TRACE Calling with one numeric for InputText and one text value;
	Call RemoveHTMLTags(5,'vCleanedHTML');
    TRACE Result: vCleanedHTML = '$(vCleanedHTML)';
    
SET ErrorMode=1;

TRACE Finished testing Sub RemoveHTMLTags;
